name: CI

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.stats()' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    env:
      MONGO_URI: mongodb://localhost:27017/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install TypeScript globally
        run: npm install -g typescript

      - name: Install @types/jest and @types/node
        run: npm install --save-dev @types/jest @types/node

      - name: Compile sample collection script 1
        run: tsc ./scripts/sampleCollection.ts

      - name: Run sample collection script 1
        run: node ./scripts/sampleCollection.js

      - name: Compile sample collection script 2
        run: tsc ./scripts/sampleCollection2.ts

      - name: Run sample collection script 2
        run: node ./scripts/sampleCollection2.js

      - name: Run tests
        run: npm test
